<?php

namespace Database\Factories;

use App\Models\Report;
use App\Models\ReportCategory;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

class ReportFactory extends Factory
{
    protected $model = Report::class;

    public function definition(): array
    {
        return [
            'reference_no'  => null, // Will be generated by observer
            'user_id'       => User::factory(),
            'category_id'   => ReportCategory::factory(),
            'title'         => $this->faker->sentence(4),
            'description'   => $this->faker->paragraph(3),
            'incident_date' => $this->faker->date(),
            'location'      => $this->faker->city(),
            'is_anonymous'  => false,
            'risk_score'    => $this->faker->numberBetween(0, 100),
            'priority'      => 'medium',
            'status'        => 'submitted',
        ];
    }
}
